version: '2'
services:
  nginx:
    build: ./nginx-1.10.3
    volumes:
    - ../:/var/www
    depends_on:
    - php
    ports:
    - "80:80"
    - "443:443"
    network_mode: bridge


  php: 
    build: ./php-7.0
    volumes:
    - ../:/var/www
    depends_on:
    - mysql
    networks:
      default:
        ipv4_address: 172.18.0.2


  mysql: 
    image: mysql:5.7.17
    volumes_from:
    - mysqldata
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=database_name
    - MYSQL_USER=user_name
    - MYSQL_PASSWORD=database_password
    - MYSQL_ROOT_PASSWORD=root_password
    networks:
      default:
       ipv4_address: 172.18.0.3

  mysqldata:
    image: debian:jessie
    volumes:
    - /var/lib/mysql
    networks:
      default:
       ipv4_address: 172.18.0.4
 

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1

