version: '2'
services:
  nginx:
    build: ./nginx-1.10.3
    volumes:
    - ../:/var/www
    depends_on:
    - php
    ports:
    - "80:80"
    - "443:443"
    network_mode: bridge


  php: 
    build: ./php-7.0
    volumes:
    - ../:/var/www
    depends_on:
    - mysql
    network_mode: bridge


  mysql: 
    image: mysql:5.7.17
    volumes_from:
    - mysqldata
    environment:
    - MYSQL_DATABASE=database_name
    - MYSQL_USER=user_name
    - MYSQL_PASSWORD=database_password
    - MYSQL_ROOT_PASSWORD=root_password
    network_mode: bridge

  mysqldata:
    image: debian:jessie
    volumes:
    - /var/lib/mysql
    network_mode: bridge
